"""init

Revision ID: d83e9e57b423
Revises: 
Create Date: 2024-05-13 09:19:35.918783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83e9e57b423'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_value', sa.String(), nullable=False),
    sa.Column('valid_input', sa.Boolean(), nullable=False),
    sa.Column('execution_time', sa.DateTime(), nullable=False),
    sa.Column('execute_duration', sa.Integer(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    # ### end Alembic commands ###
